[project]
name = "be-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "mohamedaminedarraj@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
]

[project.scripts]
be-ml = "be_ml:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
